apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicatedpool
  namespace: rook
spec:
  replicated:
    size: 3
  #erasureCoded:
  #  dataChunks: 2
  #  codingChunks: 1
  #crushRoot: default
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block
provisioner: rook.io/block
parameters:
  pool: replicatedpool