apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: nzb
  labels:
    app: nzbget
    kubernetes.io/name: "nzbget"
spec:
  selector:
    app: nzbget
  ports:
  - name: nzbget
    port: 6789
    targetPort: 6789
  type: LoadBalancer
